#!/usr/bin/env bash
#
# Install the shell into the user's application menu.
#
# Everything lands under $HOME (no root, nothing in /usr): a launcher in
# ~/.local/bin, an icon in the XDG icon theme, and a desktop entry. Re-running
# is safe — each artifact is replaced, not appended.

set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="${DSH_ELECTRON_BIN_DIR:-$HOME/.local/bin}"
APPS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
ICONS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor"
LAUNCHER="$BIN_DIR/dsh-electron"
DESKTOP_FILE="$APPS_DIR/dsh-electron.desktop"

say() { printf '  %s\n' "$*"; }

echo "Installing DeepSeek Harness desktop shell from $APP_DIR"

if [[ ! -f "$APP_DIR/src/main.js" ]]; then
  echo "error: $APP_DIR does not look like the shell (src/main.js missing)" >&2
  exit 1
fi

# 1. Launcher — a small script so the app follows edits without reinstalling.
install -d "$BIN_DIR"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Generated by dsh-electron/scripts/install.sh — edit that script, not this file.
exec "$APP_DIR/bin/dsh-electron" "\$@"
EOF
chmod 755 "$LAUNCHER"
say "launcher: $LAUNCHER"

# 2. Icons at the sizes desktop environments actually request.
ICON_SRC="$APP_DIR/build/icon.png"
if [[ -f "$ICON_SRC" ]]; then
  # ImageMagick 7 renamed `convert` to `magick convert`; support both.
  IM_CONVERT=""
  if command -v magick >/dev/null 2>&1; then IM_CONVERT="magick"
  elif command -v convert >/dev/null 2>&1; then IM_CONVERT="convert"
  fi
  if [[ -n "$IM_CONVERT" ]]; then
    for size in 48 64 128 256 512; do
      install -d "$ICONS_DIR/${size}x${size}/apps"
      $IM_CONVERT "$ICON_SRC" -resize "${size}x${size}" \
        "$ICONS_DIR/${size}x${size}/apps/dsh-electron.png"
    done
    say "icons: $ICONS_DIR/{48,64,128,256,512}x*/apps/dsh-electron.png"
  else
    install -d "$ICONS_DIR/512x512/apps"
    install -m644 "$ICON_SRC" "$ICONS_DIR/512x512/apps/dsh-electron.png"
    say "icons: $ICONS_DIR/512x512/apps/dsh-electron.png (ImageMagick absent; one size only)"
  fi
else
  say "icons: build/icon.png not found; skipping"
fi

# 3. Desktop entry.
#
# StartupWMClass must match the WM_CLASS the window actually carries, or the
# dock shows a second, unrelated icon for the running app instead of grouping
# with the launcher. Electron derives that class from the application name
# ("DeepSeek Harness" -> "deepseek-harness"), verified against a live window.
install -d "$APPS_DIR"
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=DeepSeek Harness
GenericName=AI coding agent
Comment=Desktop shell for the local DeepSeek Harness runtime
Exec=$LAUNCHER
TryExec=$LAUNCHER
Icon=dsh-electron
Terminal=false
Categories=Development;Utility;
Keywords=deepseek;harness;dsh;ai;agent;shell;terminal;
StartupNotify=true
StartupWMClass=deepseek-harness
EOF
say "desktop entry: $DESKTOP_FILE"

# 4. Refresh caches when the tools exist; both are best-effort.
if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$APPS_DIR" >/dev/null 2>&1 || true
fi
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  gtk-update-icon-cache -q -t -f "${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor" >/dev/null 2>&1 || true
fi

cat <<EOF

Installed. Start it from your application menu ("DeepSeek Harness"),
or run:  $LAUNCHER

First run notes:
  * The shell boots your own \`dsh\` and its web profile, so your existing
    sessions, plugins and credentials under ~/.dsh are used as-is.
  * Configuration lives at ~/.config/dsh-electron/config.json and is created
    on first use; the log is ~/.config/dsh-electron/dsh-electron.log.
EOF